// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBetiGck5rKmtVX7A4rs6TnnpjrNMzMqQo',
    appId: '1:753649031294:web:1cf36a475ea87c9e6ea02f',
    messagingSenderId: '753649031294',
    projectId: 'medminder-76527',
    authDomain: 'medminder-76527.firebaseapp.com',
    storageBucket: 'medminder-76527.appspot.com',
    measurementId: 'G-N36H2WL08V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5IrekDT9jX-VuwMQEBBDjdGRkquZLGBo',
    appId: '1:753649031294:android:d172b03aa03ae3476ea02f',
    messagingSenderId: '753649031294',
    projectId: 'medminder-76527',
    storageBucket: 'medminder-76527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjSJUq6-x7Oiz3eLxvPRSVa9YW0wN7614',
    appId: '1:753649031294:ios:11bdd9281c825c796ea02f',
    messagingSenderId: '753649031294',
    projectId: 'medminder-76527',
    storageBucket: 'medminder-76527.appspot.com',
    iosBundleId: 'com.example.medminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjSJUq6-x7Oiz3eLxvPRSVa9YW0wN7614',
    appId: '1:753649031294:ios:5085b95132a57b976ea02f',
    messagingSenderId: '753649031294',
    projectId: 'medminder-76527',
    storageBucket: 'medminder-76527.appspot.com',
    iosBundleId: 'com.example.medminder.RunnerTests',
  );
}
